openapi: 3.0.3
info:
  title: Clients
  version: 1.0.0
  description: clients service
servers:
  - url: /api/v1
tags:
  - name: clients
    description: Клиенты
paths:
  /clients/register:
    $ref: './clients/paths.yaml#/Register'
  /clients/create:
    $ref: './clients/paths.yaml#/Create'
  /clients/login:
    $ref: './clients/paths.yaml#/Login'
  /clients/logout:
    $ref: './clients/paths.yaml#/Logout'
  /clients/{id}:
    $ref: './clients/paths.yaml#/Get'
  /clients:
    $ref: './clients/paths.yaml#/GetClients'
  /clients/replace/{id}:
    $ref: './clients/paths.yaml#/Replace'
  /clients/delete/{id}:
    $ref: './clients/paths.yaml#/Delete'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
